# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7243702a02daa83a5d6df4150ef00f263c272e1bc3bb51204132043c40868e2717a992a53bc4654d205f9fc694cbfe8b435c0fe7e73cca4ddf8e00c1bd76fead

test:
  secret_key_base: e93b08ac5269291918c56178f124e2ff78ef554edad97fc0c3bafa8a57a7249a6925307e292fb2963f94c3a83e7856fbac3d1bf5308d35afbbac125851902720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
